version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - gocritic
    - ineffassign
    - modernize
    - staticcheck
    - unused
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
        - hugeParam
        - importShadow
        - rangeValCopy

formatters:
  enable:
    - goimports
