version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - exptostd
    - fatcontext
    - govet
    - gocritic
    - ineffassign
    - modernize
    - revive
    - staticcheck
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
        - hugeParam
        - importShadow
        - rangeValCopy
    revive:
      enable-default-rules: false
      rules:
        - name: early-return
        - name: var-naming

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      # Default: 100
      max-len: 160
