[formatter.go]
command = "goimports"
options = ["-w"]
includes = ["*.go"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.hcl]
command = "hclfmt"
options = ["-w"]
includes = ["*.hcl"]
